alias ls='ls -hF --color=tty'                 # classify files in colour
alias dir='ls --color=auto --format=vertical'
alias vdir='ls --color=auto --format=long'
alias lsl='ls -l'                              # long list
alias lsa='ls -A'                              # all but . and ..
alias hgrep='history | grep'
alias np='"/c/Program Files (x86)/Notepad++/notepad++.exe"'
alias hm='cd ~'
alias ds='cd /c/DevStuff/'
alias dsa='cd /c/DevStuff/apps'
alias uditto='cd /c/DevStuff/apps/ditto; ga .; gc -m "updated ditto"; git puom; ds'
alias ng='/c/Users/jmckenzie/AppData/Roaming/npm/ng'
alias karma='/c/Users/jmckenzie/AppData/Roaming/npm/karma'
alias ami='cd /c/src/AMI_Integrations; god; ggod'
alias amid='cd /c/src/AMI_Integrations_Deploy; god; ggod'
alias amij='cd /c/src/AMI_Integrations; godj; ggodj'
alias jfil='gb -d feature/147235-online-deploy-itmp-updates; go -b feature/147235-online-deploy-itmp-updates'
alias jfilc='ga .;gc -m "update online auto-deploy jobs for ITMP";god;ggod'
alias jfilp='git merge --no-ff feature/147235-online-deploy-itmp-updates; git push'
alias jfila='jfil;jfilc;jfilp'
alias xit='cd /c/src/MV90_Toggle_XiToggle; god; ggod'